"""Add Location, LocationStock and Product Types

Revision ID: 00931abb8b9c
Revises: d5ba2b60996d
Create Date: 2026-02-25 23:21:18.003029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00931abb8b9c'
down_revision = 'd5ba2b60996d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('location_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'product_id', name='uq_location_product')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False, server_default='hammadde'))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('to_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'locations', ['to_location_id'], ['id'])
        batch_op.create_foreign_key(None, 'locations', ['from_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('to_location_id')
        batch_op.drop_column('from_location_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.drop_table('location_stocks')
    op.drop_table('locations')
    # ### end Alembic commands ###
