"""Update ProductionRecord for BOM support

Revision ID: 240fad4e1bf2
Revises: f1a2b3c4d5e7
Create Date: 2026-03-04 00:05:35.117163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240fad4e1bf2'
down_revision = 'f1a2b3c4d5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bom_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bom_node_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.alter_column('recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_prodrec_product', 'products', ['product_id'], ['id']) 
        batch_op.create_foreign_key('fk_prodrec_bom_node', 'bom_nodes', ['bom_node_id'], ['id'])
        batch_op.alter_column('recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('product_id')
        batch_op.drop_column('bom_node_id')
        batch_op.drop_column('bom_id')

    # ### end Alembic commands ###
