"""Add vat_rate to Product model

Revision ID: c6b0cb856884
Revises: 00931abb8b9c
Create Date: 2026-03-01 22:15:07.904114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b0cb856884'
down_revision = '00931abb8b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('vat_rate')

    # ### end Alembic commands ###
