"""Add unit_cost and currency

Revision ID: d5ba2b60996d
Revises: add_indexes_ai
Create Date: 2026-02-25 21:39:55.020728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ba2b60996d'
down_revision = 'add_indexes_ai'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_locations')
    op.drop_table('product_recipes')
    op.drop_table('production_lines')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('unit_cost')

    op.create_table('production_lines',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('material_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=False),
    sa.Column('note', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('warehouse', sa.VARCHAR(length=50), nullable=True),
    sa.Column('zone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('shelf', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bin_location', sa.VARCHAR(length=20), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
